import { readFile, writeFile } from 'node:fs/promises'
import { root } from './catalog-utils.mjs'

const rows = JSON.parse(await readFile(new URL('reports/product-images.json', root), 'utf8'))
const escape = value => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;')
const groups = { foto_asignada: 'Con foto', revisar_coincidencia: 'Revisar coincidencia', sin_foto_en_fuente: 'Sin foto en la fuente', sin_codigo_comercial_valido: 'Sin código comercial válido', pendiente_busqueda: 'Pendientes de búsqueda', error_descarga: 'Descarga pendiente' }
const totals = rows.reduce((counts, row) => { counts[row.status] = (counts[row.status] || 0) + 1; return counts }, {})
const html = `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Fotos del catálogo — Expres Charlys</title>
<style>*{box-sizing:border-box}body{font:16px system-ui;margin:0;background:#f5f4ef;color:#222}header{padding:32px;max-width:1200px;margin:auto}h1{margin:0 0 12px}p{line-height:1.5}select,input{padding:12px;border:1px solid #aaa;border-radius:8px;font:inherit;margin:5px 10px 5px 0;max-width:100%}main{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:16px;max-width:1200px;margin:0 auto;padding:20px}article{background:white;padding:18px;border-radius:12px;border:1px solid #ddd}img{width:100%;height:190px;object-fit:contain}small{display:block;color:#555;margin:7px 0;overflow-wrap:anywhere}a{color:#645000}h2{font-size:17px;line-height:1.4}mark{display:block;background:#fff2bc;padding:7px;font-size:13px}article[hidden]{display:none}.counts{color:#555}</style>
<header><h1>Fotos del catálogo</h1><p>Las fotos se buscan por código de barras. Las coincidencias dudosas quedan fuera de la tienda para revisar nombre, marca y presentación. La coincidencia automática no sustituye la revisión visual.</p><p class="counts">${Object.entries(totals).map(([status, count]) => `${count} ${escape(groups[status] || status).toLowerCase()}`).join(' · ')}</p><label>Mostrar <select id="status"><option value="photos">Fotos encontradas</option><option value="all">Todos</option>${Object.entries(groups).map(([key, name]) => `<option value="${key}">${name}</option>`).join('')}</select></label><input id="query" type="search" placeholder="Buscar producto o código" aria-label="Buscar producto o código"></header><main>
${rows.map(row => `<article data-status="${escape(row.status)}" data-query="${escape(`${row.name} ${row.code}`.toLowerCase())}" data-photo="${Boolean(row.url)}" ${row.url ? '' : 'hidden'}>${row.url ? `<img data-src="${escape(row.url)}" alt="${escape(row.name)}" loading="lazy">` : ''}<h2>${escape(row.name)}</h2><small>${escape(row.code || 'Sin código')} · ${escape(row.category)}</small><mark>${escape(row.issue || groups[row.status] || row.status)}</mark>${row.sourceName ? `<p>En la fuente: ${escape(row.sourceName)} ${escape(row.sourceQuantity)}</p>` : ''}${row.sourceUrl ? `<small><a href="${escape(row.sourceUrl)}" target="_blank" rel="noreferrer">${escape(row.attribution)}</a> · <a href="${escape(row.licenseUrl)}">${escape(row.license)}</a></small>` : ''}</article>`).join('\n')}
</main><script>document.querySelectorAll('img[data-src]').forEach(img=>{img.src=(location.protocol==='file:'?'../public':'')+img.dataset.src});function filter(){const status=document.getElementById('status').value;const query=document.getElementById('query').value.toLowerCase().trim();document.querySelectorAll('article').forEach(card=>{card.hidden=!(status==='all'||(status==='photos'&&card.dataset.photo==='true')||card.dataset.status===status)||!card.dataset.query.includes(query)})}document.getElementById('status').addEventListener('change',filter);document.getElementById('query').addEventListener('input',filter);</script></html>`
await writeFile(new URL('reports/product-images.html', root), html)
console.log('Preparado reports/product-images.html')
